#!/bin/bash
clear;echo "######################################"
echo -e "   Auto installer Xderm-mini GUI\n######################################\n"
echo "Installing, Tunggu....."
mkdir -p /www/xderm /www/xderm/js /www/xderm/img /www/xderm/log /www/xderm/config
url="https://raw.githubusercontent.com/anjadcode/xderm-ws/main"
wget -O /www/xderm/index.php $url/index.php -q
wget -O /www/xderm/index.html $url/index.html -q
wget -O /www/xderm/xderm-mini $url/xderm-mini -q
chmod +x /www/xderm/xderm-mini
wget -O /www/xderm/xderm_ws.py $url/xderm_ws.py -q
chmod +x /www/xderm/xderm_ws.py
wget -O /www/xderm/go-tun2socks $url/go-tun2socks -q
chmod +x /www/xderm/go-tun2socks
ln -sf /www/xderm/go-tun2socks /usr/bin/go-tun2socks 2>/dev/null
wget -O /www/xderm/badvpn-tun2socks $url/badvpn-tun2socks -q
chmod +x /www/xderm/badvpn-tun2socks
ln -sf /www/xderm/badvpn-tun2socks /usr/bin/badvpn-tun2socks 2>/dev/null
wget -O /www/xderm/badvpn-udpgw $url/badvpn-udpgw -q
chmod +x /www/xderm/badvpn-udpgw
ln -sf /www/xderm/badvpn-udpgw /usr/bin/badvpn-udpgw 2>/dev/null
wget -O /www/xderm/badvpn_1.999.130-1_aarch64_generic.ipk $url/badvpn_1.999.130-1_aarch64_generic.ipk -q
wget -O /www/xderm/corkscrew_2.0-Rureka.com_aarch64_generic.ipk $url/corkscrew_2.0-Rureka.com_aarch64_generic.ipk -q
opkg install /www/xderm/corkscrew_2.0-Rureka.com_aarch64_generic.ipk 2>/dev/null
wget -O /www/xderm/trojan_aarch64_cortex-a53 $url/trojan_aarch64_cortex-a53 -q
chmod +x /www/xderm/trojan_aarch64_cortex-a53
ln -sf /www/xderm/trojan_aarch64_cortex-a53 /usr/bin/trojan 2>/dev/null
wget -O /www/xderm/login.php $url/login.php -q
wget -O /www/xderm/header.php $url/header.php -q
wget -O /www/xderm/config.txt $url/config.txt -q
wget -O /www/xderm/js/jquery-2.1.3.min.js $url/jquery-2.1.3.min.js -q
wget -O /www/xderm/img/image.png $url/image.png -q
wget -O /www/xderm/img/fav.ico $url/fav.ico -q
wget -O /www/xderm/img/ico.png $url/ico.png -q
wget -O /www/xderm/img/background.jpg $url/background.jpg -q
wget -O /www/xderm/xdrtheme-blue-agus $url/adds/xdrtheme-blue-agus -q
wget -O /bin/xdrauth $url/adds/xdrauth -q
chmod +x /bin/xdrauth
wget -O /bin/xdrtool $url/adds/xdrtool -q
chmod +x /bin/xdrtool
echo yes > /www/xderm/config/gotun
echo Start > /www/xderm/log/st
if [ ! -f /root/auth.txt ]; then
  echo -e "user=admin\npasswd=xderm" > /root/auth.txt
fi
echo -e "xderm-mini GUI terinstall.\n\nSilahkan Akses 'http://192.168.1.1/xderm'"
echo -e "Default Authentication\nUsername: admin\nPassword: xderm\n"
echo -e "Untuk mengganti User dan Password, silahkan edit /root/auth.txt"
echo -e "Atau jalankan command terminal xdrauth untuk mengubahnya"
echo "Jangan lupa setting config dulu di webui nya."
echo "Terima kasih -salam ryan fauzi."
